import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";

const dmMono = DM_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "FramerMotion Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
